In [1]:
import pandas as pd
import numpy as np

In [3]:
data=pd.read_csv("C:\\Users\\hi\\Downloads\\ObesityDataSet_raw_and_data_sinthetic.csv")

In [5]:
data

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,Female,21.000000,1.620000,64.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,0.000000,1.000000,no,Public_Transportation,Normal_Weight
1,Female,21.000000,1.520000,56.000000,yes,no,3.0,3.0,Sometimes,yes,3.000000,yes,3.000000,0.000000,Sometimes,Public_Transportation,Normal_Weight
2,Male,23.000000,1.800000,77.000000,yes,no,2.0,3.0,Sometimes,no,2.000000,no,2.000000,1.000000,Frequently,Public_Transportation,Normal_Weight
3,Male,27.000000,1.800000,87.000000,no,no,3.0,3.0,Sometimes,no,2.000000,no,2.000000,0.000000,Frequently,Walking,Overweight_Level_I
4,Male,22.000000,1.780000,89.800000,no,no,2.0,1.0,Sometimes,no,2.000000,no,0.000000,0.000000,Sometimes,Public_Transportation,Overweight_Level_II
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,Female,20.976842,1.710730,131.408528,yes,yes,3.0,3.0,Sometimes,no,1.728139,no,1.676269,0.906247,Sometimes,Public_Transportation,Obesity_Type_III
2107,Female,21.982942,1.748584,133.742943,yes,yes,3.0,3.0,Sometimes,no,2.005130,no,1.341390,0.599270,Sometimes,Public_Transportation,Obesity_Type_III
2108,Female,22.524036,1.752206,133.689352,yes,yes,3.0,3.0,Sometimes,no,2.054193,no,1.414209,0.646288,Sometimes,Public_Transportation,Obesity_Type_III
2109,Female,24.361936,1.739450,133.346641,yes,yes,3.0,3.0,Sometimes,no,2.852339,no,1.139107,0.586035,Sometimes,Public_Transportation,Obesity_Type_III
2110,Female,23.664709,1.738836,133.472641,yes,yes,3.0,3.0,Sometimes,no,2.863513,no,1.026452,0.714137,Sometimes,Public_Transportation,Obesity_Type_III

In [7]:
data.info

<bound method DataFrame.info of       Gender        Age    Height      Weight family_history_with_overweight  \
0     Female  21.000000  1.620000   64.000000                            yes
1     Female  21.000000  1.520000   56.000000                            yes
2       Male  23.000000  1.800000   77.000000                            yes
3       Male  27.000000  1.800000   87.000000                             no
4       Male  22.000000  1.780000   89.800000                             no
...      ...        ...       ...         ...                            ...
2106  Female  20.976842  1.710730  131.408528                            yes
2107  Female  21.982942  1.748584  133.742943                            yes
2108  Female  22.524036  1.752206  133.689352                            yes
2109  Female  24.361936  1.739450  133.346641                            yes
2110  Female  23.664709  1.738836  133.472641                            yes

     FAVC  FCVC  NCP       CAEC SMOKE      CH2O  SCC       FAF       TUE  \
0      no   2.0  3.0  Sometimes    no  2.000000   no  0.000000  1.000000
1      no   3.0  3.0  Sometimes   yes  3.000000  yes  3.000000  0.000000
2      no   2.0  3.0  Sometimes    no  2.000000   no  2.000000  1.000000
3      no   3.0  3.0  Sometimes    no  2.000000   no  2.000000  0.000000
4      no   2.0  1.0  Sometimes    no  2.000000   no  0.000000  0.000000
...   ...   ...  ...        ...   ...       ...  ...       ...       ...
2106  yes   3.0  3.0  Sometimes    no  1.728139   no  1.676269  0.906247
2107  yes   3.0  3.0  Sometimes    no  2.005130   no  1.341390  0.599270
2108  yes   3.0  3.0  Sometimes    no  2.054193   no  1.414209  0.646288
2109  yes   3.0  3.0  Sometimes    no  2.852339   no  1.139107  0.586035
2110  yes   3.0  3.0  Sometimes    no  2.863513   no  1.026452  0.714137

            CALC                 MTRANS           NObeyesdad
0             no  Public_Transportation        Normal_Weight
1      Sometimes  Public_Transportation        Normal_Weight
2     Frequently  Public_Transportation        Normal_Weight
3     Frequently                Walking   Overweight_Level_I
4      Sometimes  Public_Transportation  Overweight_Level_II
...          ...                    ...                  ...
2106   Sometimes  Public_Transportation     Obesity_Type_III
2107   Sometimes  Public_Transportation     Obesity_Type_III
2108   Sometimes  Public_Transportation     Obesity_Type_III
2109   Sometimes  Public_Transportation     Obesity_Type_III
2110   Sometimes  Public_Transportation     Obesity_Type_III

[2111 rows x 17 columns]>

In [9]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2111 entries, 0 to 2110
Data columns (total 17 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Gender                          2111 non-null   object
 1   Age                             2111 non-null   float64
 2   Height                          2111 non-null   float64
 3   Weight                          2111 non-null   float64
 4   family_history_with_overweight  2111 non-null   object
 5   FAVC                            2111 non-null   object
 6   FCVC                            2111 non-null   float64
 7   NCP                             2111 non-null   float64
 8   CAEC                            2111 non-null   object
 9   SMOKE                           2111 non-null   object
 10  CH2O                            2111 non-null   float64
 11  SCC                             2111 non-null   object
 12  FAF                             2111 non-null   float64
 13  TUE                             2111 non-null   float64
 14  CALC                            2111 non-null   object
 15  MTRANS                          2111 non-null   object
 16  NObeyesdad                      2111 non-null   object
dtypes: float64(8), object(9)
memory usage: 280.5+ KB

In [11]:
data.isnull()

,Gender,Age,Height,Weight,family_history_with_overweight,FAVC,FCVC,NCP,CAEC,SMOKE,CH2O,SCC,FAF,TUE,CALC,MTRANS,NObeyesdad
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2106,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2107,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2108,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2109,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2110,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [13]:
data.isnull().sum()

Gender                            0
Age                               0
Height                            0
Weight                            0
family_history_with_overweight    0
FAVC                              0
FCVC                              0
NCP                               0
CAEC                              0
SMOKE                             0
CH2O                              0
SCC                               0
FAF                               0
TUE                               0
CALC                              0
MTRANS                            0
NObeyesdad                        0
dtype: int64